<?php

namespace app\api\controller;

use fun\auth\Api;
use support\Request;

class Index extends Api
{
    public function __construct()
    {
        return parent::__construct(); // TODO: Change the autogenerated stub
    }

    public function index()
    {

        return response('登录账号ID：'.$this->member_id);
    }

    public function view()
    {
        return view('index/view', ['name' => 'webman']);
    }

    public function json()
    {
        return json(['code' => 0, 'msg' => 'ok']);
    }

}
